gocron.go, job.go, scheduler.go, timeHelper.go
Addressing #10 
Created a `timeHelper` interface to wrap the functions we are using from the `time` package. Not wrapping the constants like `time.Sunday` because I guess that's not necessary. 
We might not need to define a `mockTime` explicitly if we use a mocking tool like [Mockary](https://github.com/vektra/mockery).
=> add timeHelper interface to avoid direct coupling with the time package

example_test.go, gocron.go, job.go, job_test.go, scheduler.go
This is explains godocs pretty helpfully: https://godoc.org/github.com/fluhus/godoc-tricks
What the examples look like:
=> Update all exported comments and start example_test.go for godoc

job.go, scheduler.go, scheduler_test.go, timeHelper.go
```
package main
import (
"fmt"
"time"
)
func task() {
fmt.Printf("Task time: %v\n", time.Now().UTC())
}
func main() {
s1 := gocron.NewScheduler(time.UTC)
s1.Every(2).Seconds().StartImmediately().Do(task)
<-s1.Start() // starts running (blocks current thread)
}
```
Output:
```
Task time: 2020-04-10 05:13:40.606502 +0000 UTC
Task time: 2020-04-10 05:13:42.60736 +0000 UTC
Task time: 2020-04-10 05:13:44.608121 +0000 UTC
Task time: 2020-04-10 05:13:46.609026 +0000 UTC
Task time: 2020-04-10 05:13:48.606512 +0000 UTC
Task time: 2020-04-10 05:13:50.608894 +0000 UTC
Task time: 2020-04-10 05:13:52.606553 +0000 UTC
Task time: 2020-04-10 05:13:54.608598 +0000 UTC
Task time: 2020-04-10 05:13:56.606573 +0000 UTC
Task time: 2020-04-10 05:13:58.606552 +0000 UTC
Task time: …
```
=> fix bug in scheduler, rescheduling jobs immediately

scheduler.go, scheduler_test.go
Fix removeByCondition get "slice bounds out of range".
Resolves #45 
1. Adding corner case on TestRemove unit test in `schedule_test.go`
2. Changing `range` loop to traditional iteration loop on `removeByCondition` in `schedule.go` to fix slice bounds out of range.
Yes
=> Fix removeByCondition get "slice bounds out of range"

README.md, gocron.go, job.go, scheduler.go, scheduler_test.go
Add support for executing jobs every Month/Months
#43 
Doesn't break any current functionality
Yes
=> Add support for executing jobs every Month/Months

gocron.go, gocron_test.go, scheduler.go
Parse the At() time with time.Parse() instead of `Atoi`
#14 
One small change is before `6:40` would have been considered valid, but now, it has to be `06:40`.
Existing tests suffice
=> Parse the At() time with time.Parse()

scheduler.go, scheduler_test.go
Make sure Do() does not override the nextRun time when StartAt() is used
Fixes #35 
None
Yes
=> Bugfix: Make sure Do() does not override the nextRun time when StartAt() is used

job.go, job_test.go, scheduler.go, scheduler_test.go, timeHelper.go
Time scheduling was spread between job registration and actual schedule calculation, which was confusing and made testing difficult. As a matter of fact, our weekdays logic wasn't working for some edge cases and we probably had some bugs out on .Month() calculation too, although I didn't check it explicitly.
This PR rewrites our next-run scheduling logic and cover it with different tests use cases, taking in consideration weekday schedules, weekdays schedules starting immediately and exact-time schedules.
Sorry for it being big. Most of the new lines are tests cases.
This might fix #52. I cannot actually say this fixes it since I was not able to reproduce it, but nevertheless this PR fixes weekday logic.
None
Lots of, but might have missed something. Please bring it up if you can think of …
=> refact: rewriting scheduler logic

scheduler_test.go
These cases are already covered on TestScheduler_FirstSchedule. Removing these tests due cleans up the test file and makes our lives better since they were deterministic (they failed as a false positive during specific times o the day)
none
=> refact: removing legacy deterministic tests

scheduler.go, scheduler_test.go
scheduler schedules jobs registration when already running
#60 #58
=> fix: scheduler schedules jobs registration when already running

example_test.go, job.go, job_test.go, scheduler.go
Exposes a new `Job` method called  `LimitRunsTo` to control how many times a job should run
Closes #24 
Backward compatible 
Yes
Please suggest better function/struct/field names if required.
=> Add a new Job method called 'LimitRunsTo'

job.go, scheduler.go, scheduler_test.go
adds a mutex to the job struct to avoid race conditions
#73
=> add mutex to job

gocron_test.go, scheduler.go, scheduler_test.go
#79 removed the setting of last run - re-adding it. Without setting the last run, https://github.com/go-co-op/gocron/blob/master/scheduler.go#L100 is always true.
resolves #80 
yes - updated an existing test to catch this issue
=> set the job's last run in scheduler run()

README.md, example_test.go, job.go, scheduler.go, scheduler_test.go
The default behavior will now be that jobs start immediately unless scheduled at a specific time, for a specific weekday or on a specific day of the month.
=> start jobs immediately by default

example_test.go, job.go, job_test.go
Add 3 exported methods to the Job struct to expose lastRun, nextRun and runCount
Yes
=> Expose the Job's lastRun, nextRun and runCount 

job.go, scheduler.go, scheduler_test.go
- fixes a bug identified where subsequent jobs are not scheduled if the first job is evaluating false. The `break` in the for loop causes the 2nd element to never be reached. It should be `continue`
- also some spelling fixes
resolves #85 
👍
=> fix runnableJobs where subsequent jobs are never checked

scheduler.go, scheduler_test.go
Remove the placeholder job from the scheduler while returning any error from the `Do` function
Closes #84 
Yes
=> Fix: Handle job creation errors better

Makefile, example_test.go, scheduler.go, scheduler_test.go
protects the scheduler location struct field with a mutex to avoid possible data races of changing the scheduler location while the scheduler is running
=> add mutex to scheduler location

CONTRIBUTING.md
Adds a contributing md to spell out some expectations! 
resolves #17
=> Add a contributing md

job.go, scheduler.go, scheduler_test.go
Main change: scheduler now uses `time.AfterFunc` from the standard ```time``` package to schedule jobs instead of manually sorting and looping through all jobs (yes, finally!)
This brings us:
- assertion that our "run jobs" algorithm works without bugs as we're leaving this logic to a standard package
- greater flexibility in what fields we want to keep in jobs - no need to actually keep other fields like `nextRun` or even our job slice for our run logic (they may still be useful for logging or getting meta info about a job or the scheduler, so they're not removed here)
- minor performance gains as we don't sort and loop through our job array every second anymore
- increased cohesion of our scheduler package 
Unfortunately, after doing this refactor and separating the logic correctly, …
=> refact: schedules jobs with time.AfterFunc()

job.go, scheduler.go, scheduler_test.go
- fixes a bug we introduced in v0.5.0
- introduced `startAtTime` field on the job struct so we know when a job is scheduled to start at a specific time and we should go ahead and start the timer! 
#102 #98
=> fix bug with StartAt() in v0.5.0

example_test.go, scheduler.go, scheduler_test.go
Remove stopChan from Scheduler to restrict stopping the scheduler only to the Stop function
Closes #100 
The `StartAsync()` function will not return the `stopChan` anymore. This is a backward incompatible change
=> Remove stopChan from Scheduler 

scheduler.go, scheduler_test.go
when we use every month at some time,then calculate next run time use base time is not consistency
=> fix calculateMonths

scheduler.go, scheduler_test.go
This PR adds a loop to increment the Job's `startAtTime` until it is in the future. It will only need to do this if a Job is intentionally set to start in the past, not if it is just defaulted to 0.
Resolves #106 
- If someone is intentionally scheduling something to start at 0 time, it might not work as expected.
Yes
Yes
See #106 for more information
=> Allow starting Jobs in the past (#106)

scheduler.go, scheduler_test.go
- fixes the bug where a limit of runs was not stopping the job
- this was happening because `scheduleNextRun` became a recursive function, and so the checks for `shouldRun` were never called. the check happens in the `runJobs` func which is only called the first time it's started.
closes #111 
👍
=> fix bug with limit runs to not stopping jobs

example_test.go, gocron.go, job.go, scheduler.go, scheduler_test.go, timeHelper.go
Changes the `Every()` func in the scheduler allowing users to schedule any time.Duration between job runs via:
- int + unit (e.g. Seconds)
- time.Duration
- string representation of time.Duration e.g. `1s`
closes #44 
👍
=> Every() accepts int, time.Duration, string to allow any custom duration between runs

LICENSE, README.md, example_test.go, gocron.go, job.go, scheduler.go, scheduler_test.go
- adds examples for all functions
- removes all examples from the readme
- renames a few functions and changes some signatures
- moves the license to an MIT license (almost the same wording) - gets a nice standard license
resolves #95 
- The job `Tag` func now accepts a variadic string parameter instead of a slice
- The scheduler `SetTag` is now `Tag` and also accepts a variadic string parameter
- The scheduler `RemoveJobByTag` is now `RemoveByTag` to be consistent with `Remove` and `RemoveByReference`
- The scheduler `RunAllWithDelay` func now accepts a time.Duration instead of an int representing seconds
- The scheduler `Scheduled` func is now `TaskPresent` - scheduled was confusing name because until the scheduler is started, it's not actually "scheduled to run". Now you can check …
=> add examples for all funcs, license tweak, func name clarifications

README.md, executor.go, gocron.go, job.go, job_test.go, scheduler.go, scheduler_test.go
Spins up an executor that runs job functions passed to it on a chan. This changes it so that only the function of the job is passed to a separate goroutine and reduces the references to the job object by different goroutines.
resolves #101 
implicitly tested by all tests
- added a link to our examples on the go docs
=> implement executor to reduce go routines / mutexes

scheduler.go
jobs() method lock the jobs to get list of them but after we call Jobs(),this method lock jobs until get list of them, but after this method finished, the caller of this method should need lock the jobs because maybe it need to check current state and no past state, and if in this state removebytag() remove any job this may generate race condition (because used append() function on job in removebytag())
=> fix race condition

job.go, scheduler.go, scheduler_test.go
Stops all jobs in the scheduler before removing when clear is called
resolves https://github.com/go-co-op/gocron/issues/133
👍
=> clear should stop all jobs before removing

example_test.go, gocron.go, job_test.go, scheduler.go, scheduler_test.go
- when multiple errors occur, wrap them so the user can unwrap and check what happened
- collapse/clean up tests
=> wrap errors

example_test.go, gocron.go, scheduler.go, scheduler_test.go
- allows enforcing tags to be unique across the scheduler
- there isn't a good way I can see to support forcing jobs tagged via the job.Tag() method to be unique as they have no knowledge of the scheduler. I considered a global tags map, but that would then be unique across all schedulers that the user may define. Limiting the scope to a single scheduler seems better, albeit with the limitation that the scheduler.Tag() method must be used. 
#131 
👍
=> allow enforcing uniqueness across tags

.github/workflows/go_test.yml, example_test.go, gocron.go, job.go, scheduler.go, scheduler_test.go
- renamed job.Err to job. Error
- remove, removeAfterLastRun - just remove when a job hits the limit by default. we don't have any way to restart a job, so there is not point in keeping them in the scheduler once they're stopped
- add milliseconds explicitly as a unit (already available using the Every(time.Duration) option)
- allow At() to accept an interface, string or time.Time (parsing hours down if time.Time)
=> a bunch of things

gocron.go, scheduler.go, scheduler_test.go
It introduces additional validation of params in Scheduler.Do. If list of passed params doesn't correspond to original function params it returns an error.
#142 
TestScheduler_LessParamsThanExpected
TestScheduler_MoreParamsThanExpected
=> #142 validation of params is added

example_test.go, executor.go, go.mod, go.sum, gocron.go, job.go, scheduler.go, scheduler_test.go
- Adds support for rescheduling jobs using the following syntax:
```golang
func ExampleScheduler_Update() {
s := gocron.NewScheduler(time.UTC)
j, _ := s.Every("1s").Do(func() {})
time.Sleep(10 * time.Second)
j, _ = s.Job(j).Every("10m").Update()
time.Sleep(30 * time.Minute)
_, _ = s.Job(j).Every(1).Day().At("02:00").Update()
}
```
#72
=> Support rescheduling jobs

example_test.go, scheduler.go, scheduler_test.go
Add 2 new functions to Scheduler
* `RunByTag` - Run all jobs that have a specific tag
* `RunByTagWithDelay` - Run all jobs that have a specific tag with a
delay in between executions
Fix: `RemoveByTag` function should remove all jobs with the given tag. Not
just the first job encountered
Resolves #143
As mentioned above, currently, `RunByTag` only deletes the first job it finds with a given tag. But this PR modifies that behavior to delete all the jobs with the given tag.
Yes
=> Run jobs by Tag

scheduler.go, scheduler_test.go
- The lastRun time was not being set inside the schedule run function after we run the job (in the case of a job starting immediately).
- crontabs run on the minute, or hour, etc. so we don't want them to start immediately
fixes https://github.com/go-co-op/gocron/issues/153
=> fix lastRun not being set properly in schedule next run & crontabs should not start immediately

example_test.go, scheduler.go, scheduler_test.go
- explicitly sets the location for the crontab expression using `CRON_TZ` - the parse expression defaults to time.Local, which doesn't handle when a caller is setting a different timezone for the scheduler
- add a new method `CronWithSeconds()` that the parsing of seconds which robfig exposes
- i made this a separate method because standard cron expressions don't support seconds, so rather than have the `Cron()` func optionally support seconds i thought making explicit was better
=> set the scheduler location in the cron expression and add CronWithSeconds()

scheduler.go, scheduler_test.go
singleton jobs as well as waitmode jobs listen for the job context to be cancelled. `Update()` needs to clear that otherwise all subsequent runs are skipped because the context.Done() check is always true.
resolves #157
=> clear the job context for singleton on update

scheduler.go, scheduler_test.go
we see an occasional instance of a daily job running twice within a second. this seems to be due to the job running too fast and starting a fraction of a second early such that it runs during the 1 second window before it should. this fix handles that case for daily jobs as those only run once at a given even hour/min/sec time.
https://github.com/go-co-op/gocron/issues/52#issuecomment-816502678
=> handle occasional occurence of double run on daily job

example_test.go, job.go, scheduler.go, scheduler_test.go
- adds `WaitForSchedule` and `WaitForSchedules` to allow setting per job or for all jobs to wait for the first scheduled run rather than running immediately
- un-exports the job's `NewJob` method. There was no use for it to be exported as we don't accept a newly created job struct in any scheduler methods. alters the signature to handle the wait for interval logic
#152
=> add WaitForSchedule(s) funcs

example_test.go, go.mod, go.sum
=> add example for job.weekdays() and tweak scheduler week examlpes, go mod tidy

scheduler_test.go
Fix invalid test behavior that allows race conditions to happen. 
to test: `go test -race -v -count=2 -run ^TestScheduler_CheckNextWeekDay`
=> fixing invalid test behavior

scheduler.go, scheduler_test.go
Switches to using raw duration from a day-clamped duration for the difference between lastRun and jobDay.
Resolves #172
=> Fix calculatemonths()

scheduler.go, scheduler_test.go
Currently, when you create jobs with unique tags and delete by tag afterwards, the unique tag is deleted. This leads to a unique tag constraint when adding a new job with the previous unique tag.
This PR solves this issue by deleting the unique tag alongside the `RemoveByTag` method.
Delete unique tag in `RemoveByTag`
yes
Thanks for maintaining this library. We're planning to integrate it for a major feature and the tagging functionality is a game-changer :)
=> Delete unique tag alongside RemoveByTag

scheduler.go
Removing recursive read locks, which are causing the scheduler get stuck
No behavioral changes
No Tests Included, the existing tests will sufficient
Would like to say thank you very much for the wonderful library, and we are planning to use this library in one of our tools.
While we are testing this library(Stress testing), we found that the scheduler engine is getting stuck due to recursive read locks in scheduler.go: jobPresent() function. In this jobPresent() function, we are calling read lock 2 times, one is using direct call, and other one is using s.Jobs() function. 
After going through the code, I do not believe we need explicit read lock call in jobPresent(), and once we remove the explicit read locks(This is the PR), the scheduler is not getting stuck.
To demonstrate this …
=> Remove recursive read locks

scheduler.go
If scheduler is started with `TagsUnique()`, tags are cleared also after Clear.
No.
No. It's bug fix.
=> Clear: remove also tags from scheduler

scheduler.go, scheduler_test.go
`findJobsByTag` will now get only jobs with an exact tag match, not with a substring of a tag.
This will resolve the following issue.
Resolves #184
`findJobsByTag` will not match by substring
yes
=> find jobs not by substring but by exact match

scheduler.go, scheduler_test.go
after a job was updated, we didn't clear the update flag on the scheduler which caused a nil pointer exception on the creation of a new job
resolves https://github.com/go-co-op/gocron/issues/193
👍
=> handle creating a job after an update and delete

scheduler.go
Cron functions should always wait for their interval to start to behave as expected for a crontab job
resolves #202
=> wait for interval always on cron func

.golangci.yaml, job.go, scheduler.go, scheduler_test.go
The remove functions have a bug where the unique tags set at the scheduler are only removed when using RemoveByTag which isn't used by the removal that occurs when the limit runs to is reached.
Updated the removal functions so that a check occurs to see if unique tags are being used and if so, remove all of the job's tags from the unique slice.
resolves https://github.com/go-co-op/gocron/issues/210
👍
=> Fix unique tag removal

scheduler.go, scheduler_test.go
This PR replaces that `uniqueTag` map with the [sync.Map](https://pkg.go.dev/sync#Map) struct which allows safe concurrent operations against the map. Before this, scheduled jobs that executed on the same schedule were prone to causing a "concurrent map" panic.
Tests have been updated to properly use the sync.map.
This change should produce a no-op, just fixes the potential panic from jobs scheduled at the same time that require `uniqueTags`.
=> Replace tag map with thread safe sync.map

.github/workflows/codeql-analysis.yml, .github/workflows/go_test.yml
refactor workflows to consider `main` as the default branch
#215 
I think the branch restriction needs to be applied in the repo settings?
=> [chore] refactor workflows to consider 'main' as the default branch

gocron.go, scheduler.go, scheduler_test.go
only days 1 through 28 are allowed for monthly schedules
#141
=> only days 1 through 28 are allowed for monthly schedules

example_test.go, gocron.go, job.go, scheduler.go, scheduler_test.go
- adds the func `StartImmediately` to allow overriding the default behavior of a job, for example, starting a Cron job immediately vs. waiting for it's regular schedule, which is the default behavior of Cron
- renames the job mutex to be a private struct field `mu` so that a user can't lock/unlock the job
#227
=> add start immediately func

example_test.go, scheduler.go, scheduler_test.go
fix panic error  and can be set behaviour before new job created.
Resolve #230
=> Fix panic err job create before set behaviour.

executor.go, scheduler.go, scheduler_test.go
Scheduler now waits for all running jobs to finish before returning. Fixes #237. 
Fixes #237 
None.
Yes.
Yes.
=> fix: stopping scheduler waits for all jobs to finish

.github/workflows/file_formatting.yml
This PR adds a CI check to ensure `example_test.go` file is kept sorted
in alphabetical order. Note that the pipeline will fail if an example is
added or moved around such that the file is no longer sorted.
See #231 
NONE
No
Fixes #231
=> CI check for formatting

.github/workflows/file_formatting.yml
The `file_formatting.yml` file does not checkout the repository before
running, resulting in a file missing error. This PR adds the checkout
step.
See #231 
None
No
None
=> add checkout step to formatting action

scheduler.go, scheduler_test.go
This PR changes `scheduler.Tag()` to append to, rather than overwrite, existing tags
I didn't create an issue because the README mentioned small changes can just send a PR. Here are some details I would have put in the issue:
If multiple calls to `scheduler.Tag()` are chained together, only the last one called persists.
Check out [this Playground](https://play.golang.org/p/8ozf_TpCppd)
I expected multiple calls to `Tag()` to append to existing tags rather than overwrite.
This shouldn't be a breaking change unless someone is using multiple calls to `Tag()` to conditionally overwrite previous ones.
Yes
No
While this was unexpected behavior to me, I understand it might be the intended way to use Tags, in which case this can be closed.
=> Append tags rather than overwriting

job.go, job_test.go, scheduler.go, scheduler_test.go
This changes `RemoveByTag` to accept multiple tags to match. All tags must be matched by the Job to be removed.
N/A
These changes should not break any current functionality because the function name is unchanged and variadic parameter allows one or more inputs.
Yes
If it would be better to rename the function to `RemoveByTags`, I can do that, but I didn't want to make a breaking change.
=> Allow removing Jobs that match multiple tags

scheduler.go
This exports the `FindJobsByTag` function so that it can be used outside of the package. This is really useful for updating `Jobs` or displaying the `NextRun` time.
N/A
None (unless this was un-exported for a reason).
No because there is full coverage from this being used throughout the package. Let me know if I should add some specific tests.
=> Make FindJobsByTag exported

executor.go, job.go
- job cancel can be nil
- job func state can be nil
closes #269
=> catch nils on job function creation failures

gocron.go, scheduler.go, scheduler_test.go
- in the wrapOrError function checks if the error already exists in the wrapping to avoid dupes
- within the Do() func, check that the interval isn't 0 and error if it is
=> handle error case better where every/cron is not called

.gitignore, example_test.go, job.go, scheduler.go, scheduler_test.go
adds the ability to enable SingletonMode on jobs at the scheduler level
relates https://github.com/go-co-op/gocron/issues/279#issuecomment-1016803434
=> add SingletonModeAll() to enable for all jobs on scheduler

example_test.go, scheduler.go, scheduler_test.go
add RemoveByTagsAny removes jobs that match any one tag. RemoveByTags removes jobs that have ALL tags.
resolves #290 
👍
=> add RemoveByTagsAny removes jobs that match any one tag

scheduler.go, scheduler_test.go
Currently, a cron expression with tz info is not supported, the default tz for a scheduler will always be appended to the user given cron expression.
This pr changed this behavior, the default tz for a scheduler will be used only if the cron expression has no tz info
N/A
Yes
=> support different tz in one scheduler

example_test.go, scheduler.go, scheduler_test.go
It allows us to set the job to every first weekday of month
#274 
Of course.
Updated `example_test.go`
=> Add every first weekday of month (#274)

Makefile, example_test.go, gocron.go, job.go, job_test.go, scheduler.go, scheduler_test.go
- adds a new method DoWithJobDetails that expects the passed jobFunc to have the it's final function parameter be a gocron.Job
- an error is returned if the function doesn't meet this requirement
- changes the Job mutex to be inside a pointer struct inside the Job to allow copying the job struct not by pointer
- copy's the job parameters slice, since slices are by reference, to avoid a race condition with the executor calling the params
- move the schedule next run logic before running the job so the job knows it's next run during the current run
resolves #299 
closes #251 
👍 
```golang
package main
import (
"log"
"time"
)
func task(job gocron.Job) {
log.Printf("job last run: %s, this run: %s, job next run: %s", job.LastRun(), time.Now(), job.NextRun())
}
func …
```
=> add DoWithJobDetails passes a copy of the job to the jobFunc

gocron.go, job.go, scheduler.go, scheduler_test.go
Resolves #350 Job lastRun was causing the data race when RunByTag. Wraps the `job.copy` in `Scheduler.run()` into separate method, `addJobDetails` and added locks on `job.runCount`, `job.lastRun`.
Resolves #350 
Updated TestScheduler_RunByTag in `shceduler_test.go` to simulate multiple tasks being run by tag.
Added `ErrInvalidFunctionParameters     = errors.New("length of function parameters must match job function parameters")` But if this case will never be happening, update the `job.error`. Otherwise, it would be better to return the error.
=> [BUG] Fix Data race when using RunByTag

job.go, scheduler.go
This fix covers the remaining data race issue in job lastRun. 
Data race when using RunByTag
Properly protect data race condition in `runContinuous`, `neverRan`, `shouldRunAtSpecificTime` - prevents potential dead lock issue previously introduced as well.
=> Fix data race in lastRun

.github/workflows/file_formatting.yml, example_test.go, scheduler.go, scheduler_test.go, timeHelper.go
closes https://github.com/go-co-op/gocron/pull/354
resolves #353
=> expose custom time method to allow for easy testing

scheduler.go
One more optimization:
When NTP time is calibrated or a leap second occurs, the following conditions may occur:
Now: 2022-01-01T00:00:00Z
Job: 
nextRun.duration = 2*time.Mintue, 
nextRun.dateTime = 2022-01-01T00:02:00Z
//...
Now: 2022-01-01T00:02:00Z
// ntpdate
// system time is corrected
Now: 2022-01-01T00:01:58Z
```go
job.setTimer(time.AfterFunc(next.duration, func() {
if !next.dateTime.IsZero() {
for {
if s.now().Unix() >= next.dateTime.Unix() {
break
}
// ...will loop for 2 seconds
}
}
s.runContinuous(job)
}))
```
This should be better:
```go
job.setTimer(time.AfterFunc(next.duration, func() {
if !next.dateTime.IsZero() {
for {
n := s.now().UnixNano() - next.dateTime.UnixNano()
if n >= 0 {
break
}
s.time.Sleep(time.Duration(n))
}
}
s.runContinuous(job)
}))
```
=> Optimize job setTimer

scheduler.go, scheduler_test.go
This commit will call stop() on every job when the scheduler is stopped. This will prevent creating another job timer loop when the scheduler is started again.
Resolves #367  
Yes
=> Stops all jobs when stopping scheduler (fix #367)

job.go, scheduler.go, scheduler_test.go
Protect `job.RunCount()` with mutex and prevent the data race condition.
#374 
`job.RunCount()` is being protected by mutex
=> Protect job.RunCount() with mutex

.github/workflows/go_test.yml, go.mod, gocron.go
=> bump go to 1.19

example_test.go, scheduler.go, timeHelper.go
=> add CustomTimer allowing overriding of the time.AfterFunc

scheduler.go
sets the job next run calculation to go from the last run time instead of time now. then when setting the timer, subtract time now from the next run time to accommodate for the slight drift that may occur there. Also, set the last Run time to be the next run time before setting the new next run time. Then, because there are still cases where the next run comes back negative due to what appears to be some minor discrepancies in time and possibly due to the jobs running very fast, the negative duration abs is slept off and the next run is scheduled from there. 
resolves #319
=> solve issue where job intervals drift slightly

executor.go, scheduler.go
removes the job if one is created without a function and tried to run
relates #376
=> if job chains are used improperly we can end up with jobs with nil functions

executor.go, executor_test.go
Add `stoppedCh` aside from `stopCh`, which is used to wait for the executor to stop
Resolves #391.
No
=> fix logic to wait for executor stop

job_test.go
Stop should be called after the job has been scheduled.
The failure can be reproduced by
```
go test -p 4 -count=50 -v -run TestJob_SetEventListeners
```
=> Fix flaky SetEventListeners test

scheduler.go
getCurrentJob() made two calls to Jobs() and used the length of the second one to get the latest job. Jobs() uses a mutex but since it's called twice the length can change between these calls which occasionally leads to a race condition and panic. This is more if jobs are removed often.
This PR directly access jobs list in getCurrentJob and uses a single lock instead of two separate ones.
Resolves a panic.
None.
=> Fix panic in getCurrentJob()

example_test.go, job.go
I found it a bit odd that times were printed as `8:3` instead of `08:03` when using these methods, so pad them with leading zeroes for clarity.
=> job: Pad `ScheduledAtTime(s)` with leading zeroes

go.mod, scheduler.go, scheduler_test.go
This fixes a bug in how gocron schedules scheduled next day, week/weekday, month tasks. Previously, the next run was calculated by rounding the current date to midnight, adding the scheduled time ("at time" represented as a duration), and then adding the necessary day, week, or month interval. This methodology fails on daylight savings transition days. 
For example, suppose gocron was run on March 12, 2023 (first day of daylight savings time) and needs to set up a task that runs at 8pm every night. The initial calculation of the next run date time will calculate the next run by rounding the current time to midnight (March 12, 2023 at 00:00) and adding the scheduled time ("at time" of 20:00 represented as 20 hours in duration). Normally, this yields 8pm but since daylight savings time …
=> Fix a bug with scheduling next runs on daylight savings change days

.github/workflows/go_test.yml, .golangci.yaml, scheduler.go, scheduler_test.go
=> handle case where last run would be in the future on a job update

example_test.go, scheduler.go, scheduler_test.go
This PR adds a function for getting all tags.
Imagine you have a database table of thousands of SQL queries you need to run according to their configured crontab schedules, and you have a service that fetches these configs and uses gocron to schedule each query to execute. This service also polls the database on a schedule to sync the configured query configs with corresponding jobs in the gocron scheduler. It would be nice to have some sort of `GetAllTags()` function so that if you needed to delete jobs that no longer need to run, you can compare the list of all tags to the list of all newly fetched query configs.
```golang
scheduler := gocron.NewScheduler(time.UTC)
scheduler.TagsUnique()
// map of active queries to schedule
queryConfigs := map[string]string{
"query1": "select * from …
```
=> add func for getting all tags

scheduler.go, scheduler_test.go
in our nextrun calculation, only run using the startat time if At() isn't set. This bug only surfaced if you were using weekday (possibly other places, but I couldn't find others) and would cause a job to run before the actual first At time should be. In this case, `StartAt()` really behaves as a "startAfter". The At() time will be scheduled at the first instance after the `StartAt()` time.
resolves #399
=> fix issue where Weekday(), StartAt() and At() set at the same time result in unexpected run times

example_test.go, executor.go, executor_test.go, job.go, job_test.go, scheduler.go, scheduler_test.go
1. replaces the limiter.singleflight with the `singletonRunner()` func that is spun up in a goroutine per singleton job. The singelton runner handles checking the `singletonQueue` to see if requests to run have been made for that specific job func
1. changes the jobState to be a atomic.Bool and named `isRunning` to more accurately reflect what it's tracking
1. moves runCount onto the jobFunction to allow incrementing to occur in the executor using an atomic.Int64 - makes it accurate in cases where the job execution is limited
note in the results in this example that the number of goroutines does not exceed 4/5 goroutines which are:
- scheduler
- executor
- executor task for job1 (sometimes we catch it in the print, hence 4 or 5)
- executor task for job2
- and the singletonRunner
when job1 …
=> fix singleton mode to avoid goroutine leaks, and accurate run counts

executor.go, executor_test.go, job.go, scheduler.go
rather than using two channels to send a `stop` and then respond with a `stopped` communication, this uses a context with cancellation and wait groups to handle stopping and then waiting for the goroutines to complete. 
resolves #425
=> rework the exectuor stopping to use context with cancel and wait groups instead of stop chans

README.md, executor.go, executor_test.go, job.go, scheduler.go, scheduler_test.go
the existing limit mode was leaking goroutines due to the implementation spinning up a goroutine for each job whether or not it is blocked. So if there a lot of jobs being queued the goroutines will pile up.
this implementation uses a single goroutine limited job runner that reads jobs from a mutex protected slice and runs then when slots are available within the max concurrent runs limit.
Also, some minor test clean up / refactoring
Example:
```go
package main
import (
"log"
"runtime"
"time"
)
func main() {
s := gocron.NewScheduler(time.UTC)
s.SetMaxConcurrentJobs(1, gocron.WaitMode)
log.SetFlags(log.LstdFlags | log.Lmicroseconds)
s.Every("1s").Do(func() {
log.Printf("job 1 start. grc: %d\n", runtime.NumGoroutine())
time.Sleep(2 * time.Second)
log.Printf("job …
```
=> refactor the max concurrent jobs executor func

executor.go, job.go, scheduler.go
TIL - using a `default` statement in the select causes 100 cpu usage -> [stack article](https://stackoverflow.com/questions/55367231/golang-for-select-loop-consumes-100-of-cpu)
resolves #457 
All tests continue to pass. An example (from the bug issue this closes)
```go
package main
import (
"log"
"time"
)
func main() {
s := gocron.NewScheduler(time.UTC)
log.SetFlags(log.LstdFlags | log.Lmicroseconds)
s.Every("1s").SingletonMode().Do(func() {
log.Println("hello from job 1")
})
s.Every("1s").SingletonMode().Do(func() {
log.Println("hello from job 2")
})
s.StartBlocking()
}
```
Dockerfile
```
FROM golang:1.20-alpine
COPY . /home/gocron_test
WORKDIR /home/gocron_test
RUN go mod vendor
RUN go build -o gocron_test .
ENTRYPOINT [ "./gocron_test" ]
```
```
docker …
```
=> fix singleton and limit modes

.github/workflows/go_test.yml, go.mod, go.sum
Small PR that upgrades Go to the latest version 1.20 in: 
* `go.mod` (+ ran `go mod tidy`) 
* `go_test.yml` Github Workflow
N/A
N/A
N/A
=> fix(go.mod): upgrade go version to 1.20

executor.go
The root cause is we write the limitModeFuncsRunning(a wait group) in the new goroutine, so the Go data race detector will think they have the data race due to reading and writing in different routines.
I'm sorry for didn't run tests in data race mode in the previous PR. @JohnRoesler 
Fix the data race in https://github.com/go-co-op/gocron/actions/runs/4905158223/jobs/8758756592
None
None
=> Fix data race in executor with enabling the limit mode

scheduler.go
This is a scenario that occurs with a very small probability. The `StartBlocking()` and `Stop()` methods are executed almost concurrently. When the stop is notified through the channel, the start has not been monitored, so a deadlock problem occurs.
When will the stop method and start be executed concurrently, such as closing gocron after receiving a linux signal.
=> fix: deadlock for blocking channel

example_test.go, executor.go, executor_test.go, go.mod, go.sum, gocron.go, gocron_test.go, job.go, job_test.go, scheduler.go, scheduler_test.go
moves support back down to golang 1.16.
the only features from go 1.20 that were being used were the new atomic values (which the uber package previously provided) and `any` instead of `interface{}`, but not actually using any generics here.
resolves #483
=> move support back for go 1.16

scheduler_test.go
Harden the test case in the scheduler: https://github.com/go-co-op/gocron/actions/runs/4954831163/jobs/8863682337
None
=> Harden the scheduler test case

example_test.go, job.go, job_test.go, scheduler.go
adds a new method to Job: `PreivousRun()` to expose the job run time prior to `LastRun()`
=> add Job.PreivousRun() to expose the job run time prior to LastRun()

example_test.go, scheduler.go, scheduler_test.go
the code would panic already. in this case we'll pre-empt it and panic with a useful message so the caller knows why
resolves #500
=> provide a better panic message when no jobs in scheduler and start blocking called

example_test.go, scheduler.go, scheduler_test.go
Reverts go-co-op/gocron#501
There are cases where it can be called and not cause a deadlock, so I'm just going to leave it alone for now.
example:
```go
package main
import (
"log"
"time"
)
func main() {
go func() {
for {
time.Sleep(time.Second)
log.Println("doing something")
}
}()
s := gocron.NewScheduler(time.UTC)
s.StartBlocking()
}
```
=> Revert "provide a better panic message when no jobs in scheduler and start blocking called"

scheduler.go
makes sure we won't try and divide by zero
resolves #486 
relates #282 #294 #340
=> check if the duration is zero before dividing

.github/workflows/go_test.yml, scheduler.go, scheduler_test.go
=> upgrade to golangci lint 1.53.1

executor.go, job.go
=> fix race occurrence with single queue in executor

.github/workflows/codeql-analysis.yml
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#scanning-on-push
=> chore: don't do codeql scanning on push for dependabot branches

executor.go, job.go
a possible race condition could occur with the job function's sync.WaitGroup being accessed from multiple goroutines
- the initial creation (in the scheduler goroutine)
- the adding within the executor goroutine)
- the waiting within the executor stop goroutine (which could be different from the scheduler stop if stop is called from another goroutine by the user)
resolves #507
=> bugfix: protect the job function's waitgroup with a mutex to avoid race conditions

example_test.go, executor.go, gocron.go, job.go, job_test.go, scheduler.go
deprecates the `SetEventListeners` function in favor of a more flexible function `RegisterEventListeners` that accepts a variadic list of `EventListener` to allow for expansion of event listeners in the future.
relates to #515 
deprecates the `SetEventListeners` function 
TODO: add ability to enable globally
=> add new RegisterEventListeners using new EventListener type

example_test.go, executor.go, scheduler.go, scheduler_test.go
=> add pause job execution on the scheduler

job.go, scheduler_test.go
=> fix job with details run times with singleton mode

.golangci.yaml, job.go, scheduler.go, scheduler_test.go
=> fix update when used with DoWithJobDetails

gocron.go, scheduler.go, scheduler_test.go
Hi,
Merging this pull request can add the ability to pass the pointer of func in `Do()` method.
Example:
```go
fn := func() { fmt.Println("Hi") }
_, err := s.Every(1).Second().Do(&fn)
fmt.Println(err)
// nil
_, err = s.Every(1).Second().Do(fn)
fmt.Println(err)
// nil
```
I have added a test for that, and it works properly and is also backward compatible.
If you have any ideas or concerns regarding the PR, feel free to tell me.
=> feat: handle pointer to func

example_test.go, go.mod, go.sum, gocron.go, job.go, scheduler.go, scheduler_test.go
- adds a uuid to each job
- changes the scheduler jobs slice to be a map
- this increases job removal performance, can be by ID now
- also makes several other looks up more efficient doing map key lookup instead of looping slice 
resolves #526 
- removes the Swap and Less methods on the scheduler that were implemented for sorting jobs
=> add job uuids and change scheduler job slice to map

example_test.go, job.go, scheduler.go, scheduler_test.go
=> put Jobs() back to returning slice and add JobsMap()

job.go, scheduler.go, scheduler_test.go
- currently 7am, run a schedule for every 2 days at 9am and 11am -> should run at 9am and 11am on the day the scheduler was started
- currently 12 noon, run a schedule for every 2 days at 9am and 11am -> should run at 9am and 11am two days after the scheduler started
resolves #552 
The initial scheduling of jobs using At time changed to be more intuitive (see the description above)
=> every X days should run on the same day if the At() time has yet to come

scheduler.go
a bug was introduced in #542 that this PR fixes. when calculating the next run it didn't take into account multiple negative days and only considered the last day of the month
resolves #554
=> more than 1 day before last day of month gets stuck in a loop

executor.go, scheduler_test.go
=> fix: block unlock with limit concurrency

scheduler.go
=> fix: data race for get jobs map

executor.go, locker.go, scheduler.go, scheduler_test.go
Sometimes, we need gocron to support active-standby mode. Only the active instance can run jobs, and other instances are just backup instances. Only when there is a problem with the master instance can other backup instances run jobs.
we can use  libs to implement election interface, e.g. `etcd election`、`k8s leaderelection`、`consul`、 `zk` and `redis lock`.  😁
It is recommended that gocron can give users more choices, allowing users to choose distributed locks and distributed election solutions according to their needs. 
Of course, the distributed lock solution is also very good, each gocron instances try to acquire lock, each gocron instaces can run jobs with probability.
The advantage of election is that all tasks are executed on one instance, and more business optimization operations …
=> feat: add election leader

executor.go, scheduler.go
* Remove line break between docs and `WaitMode` enum, so it shows up in pkg.go.dev documentation.
* Fixes typo in docs for `Scheduler.Millisecond()` and `Scheduler.Milliseconds()` functions.
N/A
N/A
N/A
N/A
=> docs: fix WaitMode and Milliseconds documentation

executor.go, scheduler_test.go
before running a job in the limit mode runner, we need to check that the context isn't cancelled. If it is, obviously don't run the job
=> fix removing a job not stopping with limit mode

example_test.go, job.go, job_test.go
adds the GetName() func to the job
resolves #582
=> add GetName() to Job to expose job name

scheduler.go, scheduler_test.go
fix: scheduler error when using every() func not following setting problem.
#587 
just run `go test -v --run ./...`
only modifies current tests.
n/a
n/a
=> fix: scheduler error when using every() func not following setting problem

job.go, scheduler.go, scheduler_test.go
the root cause of this issue is wrong logic. it should use the weekday to calculate instead of a job.RunCount.
if job.RunCount run over the setting days and it'll encounter an error
fix #590 <br/>
only fix bugs for schedule. if it executes though all weekdays one time, the behavior will change. <br>
ex: user sets. `.Every(2).Weeks().Monday().Tuesday().At("10:00")`.  then after executing Monday and Tuesday, the bug will show up. In the next round, after executing on Monday it will wait 2 weeks for execution on Tuesday
yes, adjusted existing testing
n/a
=> fix: set multi-weekdays bug about issue-590
