- .github/workflows/branchcleanup.yml
Keep our list of branches clean
> Add an action to delete branches upon merge

- README.md
- scheduler.go
the done value doesn't matter. So let's use an empty struct which consumes no memory
> use empty struct for chan

- scheduler.go
The `mustInterval` function is not doing anything. The is only validating the `interval` but we are not checking the `err` that it returns. So, this is ineffective.
> Remove mustInterval as it is ineffective

- README.md
Adds godoc badge to README so that users can easily access godoc references.
> Add godoc badge to README

- example_test.go
#16 
Moved some of the important examples from README to example_test.go (verified the generated doc). Let me know if I've missed anything.
> Add examples from README to example_test.go

- .github/workflows/go_test.yml
Let's test the latest golang version
> add go 1.15 to testing matrix and remove 1.13

- .github/workflows/go_test.yml
- .golangci.yaml
- job.go
- scheduler.go
- scheduler_test.go
- adds golangci to actions - this runs a lot of great linters on our code!
- addresses all the linting comments
closes #97
> add golangci to actions - and address lint issues

- .github/workflows/go_test.yml
> re-add tests to actions

- .github/workflows/go_test.yml
- go.mod
- go.sum
> to go 1.16

- .github/workflows/codeql-analysis.yml
> add suggested code scanning

- .github/dependabot.yml
> Add dependabot for actions and go deps

- README.md
- example_test.go
- go.mod
- go.sum
- gocron.go
- job.go
- scheduler.go
- scheduler_test.go
- imports robfig's cron to handle parsing cron expressions
- tests for cron expressions and error cases when the wrong functions are chained together
> add support for cron expressions

- README.md
> Add start example

- scheduler.go
Optimization: instead of iterative adding duration to startAtTime, add it in one operation.
E.g if jobs startsAt year 1970 every minute. And we'll try add this job scheduler. It takes around 30s on my local machine, just to compute time in the future.
No. Existing tests works.
> Optimize computing startAtTime in the future

- scheduler.go
- scheduler_test.go
the cron function wasn't handling the case of the job being updated. now it does
resolves #190 
:+1:
> Update() func supports crontab funcs

- scheduler.go
- scheduler_test.go
> wait for interval respected by cron func

- example_test.go
- executor.go
- job.go
- job_test.go
add IsRunning() to report the job's state
#225 
👍
> add IsRunning() to report the job's state

- README.md
> fix some wording and formatting

- go.mod
> upgrade to go 1.17

- executor_test.go
- gocron_test.go
Add tests for executor and gocron reflection
> added tests for executor and gocron

- example_test.go
- scheduler.go
- scheduler_test.go
I've added a basic implementation of .Midday() function to allow set a task time to 12:00
Please, feel free to review my PR. Let me know if I missed something.
> Add .Midday() to schedule a task at 12:00 (#254)

- scheduler.go
- scheduler_test.go
fix #171
Yes.
`remainingDaysToWeekday` is a bit confusing, I rewrite it.
> fix weekday duration calculation error

- scheduler.go
Fixes the [issue 308](https://github.com/go-co-op/gocron/issues/308)
> fixes #308

- example_test.go
- executor.go
- gocron.go
- job.go
- job_test.go
Added event listeners on  before job executing and after job executing. #315 
Tests are included.
`example_test.go` updated
> add event listeners on before and after job executing

- scheduler.go
fixes the  deadlock when starting / stopping the scheduler more than once due to the stopChan being used improperly. The stopChan was only being listened to in the StartBlocking func and so when someone started asyc and stopped and started and then stopped the 2nd time it tried to send another message on the buffered channel which still had a message on it which was never read.
resolves #355
> fix deadlock when starting / stopping the scheduler

- example_test.go
- executor.go
- executor_test.go
- gocron.go
- gocron_test.go
- job.go
- job_test.go
- scheduler.go
- scheduler_test.go
Just getting rid of old way of using any type and callbacks test fixed.
> Refactor any type / fix for callback test

- go.mod
- go.sum
- scheduler_test.go
This PR attempts to fix flaky test on test case testAt
https://github.com/go-co-op/gocron/issues/414
- Call `s.Stop()`
- goleak
No
None
> Fix flaky testAt

- scheduler_test.go
> fix couple of tests that are flakey due to timing

- scheduler.go
- scheduler_test.go
> fix issue where At() without StartAt() never ran

- scheduler.go
- scheduler_test.go
> when Week() is called without At(), but StartAt() is called, use StartAt() offset

- scheduler.go
- scheduler_test.go
> fix random interval where lastRun ends up in the past

- example_test.go
- executor.go
- executor_test.go
- job.go
- job_test.go
- scheduler_test.go
> add FinishedRunCount() to job

- README.md
> Add star history to readme

- .golangci.yaml
- executor_test.go
- gocron_test.go
- scheduler_test.go
> update golangci-lint rules

- README.md
Let users know that gocron also supports seconds-level cron spec.
> docs: add CronWithSeconds example in readme.md

- scheduler.go
Use atomic.bool to replace lock operations。
> fix: atomic.Bool for scheduler.running

- executor.go
- scheduler_test.go
As the title described, the distributed locking limit didn't take effect if the max concurrent jobs were set at the same time.
None
Yes
> Fix the distributed locking didn't take effect if the max concurrent jobs was set

- executor.go
clears the limitModeQueue chan on stop, and recreates on start
if you stop the scheduler, and then start it again, jobs that were queued will run when you start the scheduler again, even if the jobs have been removed
> fix: clear the limitModeQueue chan on stop

- executor.go
- executor_test.go
- gocron.go
- gocron_test.go
- job.go
- scheduler.go
- scheduler_test.go
> Add support of creating the lock key for the job when the distributed lock was enabled

- scheduler_test.go
> fix the flakey at time tests

- executor.go
- lockers/redislock/docker-compose.yml
- scheduler.go
> replace time sleep instances with time after / ctx done select

- executor.go
😁 just to make the code more robust. avoid timer leaks ? 😅
> fix: add timer stop to avoid leak

- scheduler.go
> docs: code comment for Name()

- README.md
- scheduler.go
relates to: https://github.com/go-co-op/gocron/issues/202#issuecomment-1546542477
> clarify in docs that Every starts immediately

- executor.go
Simple fix for recover panic from jobs.
I moved the recoverer part from `run()` to `runJob()`
Resolves #535 
I found nothing, but all test passed, please take look at it.
Yes, i ran `make test` and `make lint` and it all passed.
> Fixed non working panic recoverer

- scheduler.go
- scheduler_test.go
* See https://github.com/go-co-op/gocron/issues/539
* Created this to make an example fix
> Possible data race fix

- example_test.go
- gocron.go
- scheduler.go
- scheduler_test.go
> support monthly schedules counting backwards from end of month

- scheduler.go
- scheduler_test.go
> don't accept a *Job in Job for Update if the ptr address doesn't match

- README.md
- scheduler.go
> add additional documentation for wait for schedule

- README.md
add stop and stopBlockingChan function in readme.md
> docs: add stop and stopBlockingChan function

- README.md
add WithDistributedElector usage in readme.md. 😁
> docs: add WithDistributedElector usage

- .github/workflows/codeql-analysis.yml
- .github/workflows/file_formatting.yml
- .github/workflows/go_test.yml
> main branch renamed to v1

- .github/workflows/codeql-analysis.yml
- .github/workflows/file_formatting.yml
- .github/workflows/go_test.yml
> main branch renamed to v1 (#593)
